name: Generate NZPortable Nightlies.
on:
  schedule:
  - cron: 0 7 * * *
  workflow_dispatch:
  
jobs:
  Generate-Nightly:
    runs-on: ubuntu-latest
    container:
      image: sharkwouter/pspdev
    steps:
      - uses: actions/checkout@v2
      - name: Get apt ready
        run: |
          apt update
          apt install -y zip unzip wget curl git jq
      - name: Assemble Archives
        continue-on-error: false
        working-directory: ./
        run: |
          ./generate-nightly.sh ${{ secrets.GITHUB_TOKEN }}
      - name: Get Build Date
        id: date
        run: echo "::set-output name=date::$(cat release_version.txt)"
      - name: Delete Old Release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{ steps.date.outputs.date }}
          tag_name: nightly
          body_path: changes.txt
          draft: true
          prerelease: false
      - name: Upload 3DS Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/nzportable-3ds.zip
          asset_name: nzportable-3ds.zip
          asset_content_type: application/zip
      - name: Upload Linux32 Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/nzportable-linux32.zip
          asset_name: nzportable-linux32.zip
          asset_content_type: application/zip
      - name: Upload Linux64 Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/nzportable-linux64.zip
          asset_name: nzportable-linux64.zip
          asset_content_type: application/zip
      - name: Upload LinuxARM64 Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/nzportable-linuxarm64.zip
          asset_name: nzportable-linuxarm64.zip
          asset_content_type: application/zip
      - name: Upload LinuxARMHF Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/nzportable-linuxarmhf.zip
          asset_name: nzportable-linuxarmhf.zip
          asset_content_type: application/zip
      - name: Upload PSP 32MB Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/nzportable-psp-32mb.zip
          asset_name: nzportable-psp-32mb.zip
          asset_content_type: application/zip
      - name: Upload PSP 64MB Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/nzportable-psp-64mb.zip
          asset_name: nzportable-psp-64mb.zip
          asset_content_type: application/zip
      - name: Upload NX Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/nzportable-switch.zip
          asset_name: nzportable-switch.zip
          asset_content_type: application/zip
      - name: Upload PS VITA Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/nzportable-vita.zip
          asset_name: nzportable-vita.zip
          asset_content_type: application/zip
      - name: Upload WIN32 Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/nzportable-win32.zip
          asset_name: nzportable-win32.zip
          asset_content_type: application/zip
      - name: Upload WIN64 Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/nzportable-win64.zip
          asset_name: nzportable-win64.zip
          asset_content_type: application/zip
      - name: Upload Build Version TXT
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/build-version.txt
          asset_name: build-version.txt
          asset_content_type: text/example
      - name: Publish Release
        uses: StuYarrow/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.create_release.outputs.id }}
